name: 42TESTERS-PRINTF

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
        working-directory: ./testers/42TESTERS-PRINTF/srcs
      - name: runtest
        run: bash ./runtest.sh
        working-directory: ./testers/42TESTERS-PRINTF
