name: FT_PRINTF_TEST

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make run
        working-directory: ./testers/FT_PRINTF_TEST
