name: PFT_2019

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make re
        working-directory: ./ft_printf/pft_2019
      - name: run_test
        run: ./test
        working-directory: ./ft_printf/pft_2019
      - name: results.txt
        run: cat results.txt
        working-directory: ./ft_printf/pft_2019
